name: My-GitHub-test

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY_ID}}
  APP_TAG: "app-version-${{ github.sha }}"

jobs:
  my-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello message
        run: echo "Hello, world!!!!"

      - name: Show folders
        run: ls -l

      - name: Show terraform version
        run: terraform --version

      - name: Show SHA
        run: echo "app-ver = ${{ env.APP_TAG }}"

  my-deploy:
    runs-on: ubuntu-latest
    needs: [my-testing]

    steps:
      - name: Print Deploy
        run: echo "Hello, world from Deploy!!!"
