name: My-GitHub-test

on:
  push:
    branches: [dev, staging, prod]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
    shell: bash
    run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ needs.build.outputs.branch == 'dev' }}
    steps:
      - name: deploy-dev
    uses: actions/download-artifact@v2
    
      name: app-build
      - run: echo "Hello, world from deploy-dev!!!!"

 
# jobs:
#   my-testing:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Print Hello message
#         run: echo "Hello, world!!!!"

#       - name: Show folders
#         run: ls -l

#       - name: Show terraform version
#         run: terraform --version

#       - name: Show SHA
#         run: echo "app-ver = ${{ env.APP_TAG }}"

#   my-deploy:
#     runs-on: ubuntu-latest
#     needs: [my-testing]

#     steps:
#       - name: Print Deploy
#         run: echo "Hello, world from Deploy!!!"
